// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FOSSIL","status":true,"description":"Fossil is an interoperability layer for RMMZ, designed to make MV plugins work in MZ. \r\nSo far, we support over 300 plugins.  You can help!","parameters":{}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"Community_Odometer_Snippet","status":true,"description":"(Community Snippet) Free HUD Maker / Odometer script for Era 1.","parameters":{}},
{"name":"MOG_ChronoEngine","status":true,"description":"(Community Snippet) Moghunter Chrono Engine Port","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"VisuMZ_0_CoreEngine","status":true,"description":"(VisuStella) Foundation for the VisuStella MZ library.","parameters":{}},
{"name":"VisuMZ_1_BattleCore","status":true,"description":"(VisuStella Free Tier) Battle Core & Skills/States Core","parameters":{}},
{"name":"VisuMZ_1_EventsMoveCore","status":true,"description":"Core movement and eventing enhancements for RPG Maker MZ.","parameters":{}},
{"name":"VisuMZ_2_QTE_TriggerSys","status":true,"description":"Action command system for Era 5 combat.","parameters":{}},
{"name":"VisuMZ_4_BattleSystemCTB","status":true,"description":"Conditional Turn-Based Battle System for RPG Maker MZ.","parameters":{}}
];
