// Generated by RPG Maker MZ.
var $plugins =
[
{"name":"FOSSIL","status":true,"description":"Fixing Old Software / Script Interoperability Layer","parameters":{}},
{"name":"VisuMZ_0_CoreEngine","status":true,"description":"Foundation for the VisuStella MZ library.","parameters":{}},
{"name":"VisuMZ_1_BattleCore","status":true,"description":"Battle Core & Skills/States Core (Free Tier)","parameters":{}},
{"name":"MOG_ChronoEngine","status":true,"description":"Seamless ATB Combat Engine","parameters":{}},
{"name":"Community_Odometer_Snippet","status":true,"description":"Rolling HP Odometer for Era 1","parameters":{}}
];
